### PR TITLE
WIP Feat/138 add direction

### PR DESCRIPTION
**Pull request by zhenglinxiao**
# Summary

WIP - just so we can see the progress

Sibo created the Directions component layout & handled the API call to MapBox, integrating title, time, and distance into the component. Also added a direction button to the mural form which opens the Directions page. 

I fetched scaled the component to handle many coordinates (up to 25 given the API specs). I fetched the direction steps from the MapBox API and integrated them into the component. `CustomSteps` takes care of the specific steps in each subroute between waypoints. `CustomLegs` takes care of adding an arrival node at the end of a subroute. Also implemented directions to a mural (when directions is clicked on a mural form) to display the directions from the current geolocated position to the coordinates of the selected mural.

Left to do:
- adjust icons in directions -> done
- add mural pic at arrival list item
- add directions button to tour form & integrate tours directions (probably a new issue)

## Test Plan

image

image

## Related Issues

#138

### CODE REVIEW

**Comment by tedspare** [comment]
This looks really good so far! Keep at it! I'm impressed by the degree of low-level date/distance parsing and thoughtful integration into the rest of the app.

A few things:
- Thanks to whoever finally added the mural interface haha this closes #128 
- Going forward, let's add JSDoc to methods and longer `useEffect`s ([example](https://github.com/hack4impact-mcgill/mu-map/blob/main/frontend/src/DragDrop/DragDrop.tsx#L53))
- There are some merge conflicts in `MuralForm` bc of my PR - I can resolve these after the dust has settled if needed
- Nitpicking here but remember to add a space before units like `1 km` or `2 hr`

**Comment by SiboYang** [comment]
> This looks really good so far! Keep at it! I'm impressed by the degree of low-level date/distance parsing and thoughtful integration into the rest of the app.
> 
> A few things:
> 
>     * Thanks to whoever finally added the mural interface haha this closes #128
> 
>     * Going forward, let's add JSDoc to methods and longer `useEffect`s ([example](https://github.com/hack4impact-mcgill/mu-map/blob/main/frontend/src/DragDrop/DragDrop.tsx#L53))
> 
>     * There are some merge conflicts in `MuralForm` bc of my PR - I can resolve these after the dust has settled if needed
> 
>     * Nitpicking here but remember to add a space before units like `1 km` or `2 hr`

I added the mural interface, but I am not sure if it's correct. Since the mural object we receive from backend and we used in the mural form are slightly different in the coordinate part (in mural form we use two separate keys "longitude" and "latitude" but what we received from the backend API call use a coordinates object), should we create two interfaces for these two cases or I misunderstand something?

**Comment by tedspare** [comment]
> > This looks really good so far! Keep at it! I'm impressed by the degree of low-level date/distance parsing and thoughtful integration into the rest of the app.
> > A few things:
> > ```
> > * Thanks to whoever finally added the mural interface haha this closes #128
> > 
> > * Going forward, let's add JSDoc to methods and longer `useEffect`s ([example](https://github.com/hack4impact-mcgill/mu-map/blob/main/frontend/src/DragDrop/DragDrop.tsx#L53))
> > 
> > * There are some merge conflicts in `MuralForm` bc of my PR - I can resolve these after the dust has settled if needed
> > 
> > * Nitpicking here but remember to add a space before units like `1 km` or `2 hr`
> > ```
> 
> I added the mural interface, but I am not sure if it's correct. Since the mural object we receive from backend and we used in the mural form are slightly different in the coordinate part (in mural form we use two separate keys "longitude" and "latitude" but what we received from the backend API call use a coordinates object), should we create two interfaces for these two cases or I misunderstand something?

In a larger project, they use DTOs ([Data Transfer Objects](https://en.wikipedia.org/wiki/Data_transfer_object)) and DAOs ([Data Access Objects](https://www.geeksforgeeks.org/data-access-object-pattern/)) for all data being passed between the frontend and backend. I believe these would have the shared/common properties of the objects used in the frontend and returned from the API.

For now, either two interfaces or a more general coords type should work.

**Review by tedspare — APPROVED** [review]

**Review by tedspare — APPROVED** [review]
LGTM, nice way of showing the right arrow

**Comment by tedspare** [comment]
A few TS warnings then Vercel will deploy:
Screen Shot 2021-03-30 at 12 15 21 PM

**Comment by SiboYang** [comment]
added mural pic and "you are here" text, haven't figure out a way to make the text algined :( maybe something to be done in the future
Screen Shot 2021-04-02 at 3 27 47 PM
Screen Shot 2021-04-02 at 3 27 34 PM

**Review by SiboYang — APPROVED** [review]
added a few changes, the rest things LGTM!

**Review by tedspare — APPROVED** [review]
LGTM. I'm getting a bug where directions only show up after I switch tabs then come back. To be fixed.

**Pull request merged**
